site_name: GermanDactyl Dokumentation
copyright: Copyright &copy; 2023 Paul Schwarz

repo_name: GermanDactyl
repo_url: https://github.com/pavl21/GermanDactyl
edit_uri: https://github.com/pavl21/GermanDactyl/main/docs

theme:
  name: material
  language: de
  logo: assets/images/logo.png
  features:
    - toc.integrate
    - content.code.annotate
  favicon: assets/images/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      schema: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Zum dunklen Modus wechseln
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Zum hellen Modus wechseln

extra:
  generator: true
  social:
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@paul_schwarz_
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Paul_Schwarz_
    - icon: fontawesome/brands/discord
      link: https://discord.com/users/289810872396808193
    - icon: fontawesome/solid/globe
      link: https://sierra-dev.de/

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Start: index.md
  - Installation: installation.md
  - GermanDactyl Setup: guides/setup.md
  - Addons:
        - Bald: 404.md
  - Guides:
      - Update ausführen: guides/update.md
      - Übersetzungen einreichen: guides/contribute.md
  - Fehlerbehebung: troubleshooting.md
  - FAQ: faq.md
